### ISSUE TITLE
Greyhole log shows email notifications being sent but where do they go?

### ISSUE THREAD

**Issue by taa1** [gboudreau/Greyhole#168]
In `greyhole.conf` I have email_to set to a local user and I see in `greyhole.log` where it is sending email notifications so I thought everything was set up OK. But on further checking my Fedora 23 install didn't have a default mail transfer agent (MTA) installed so nothing shows up in `/var/spool/mail`.

1. When there is no MTA, what does Greyhole do with the email notifications that `greyhole.log` says it is sending?

2. Is there perhaps an untrapped error happening that just isn't being handled and/or reported by Greyhole in `greyhole.log`?

**Comment by gboudreau** [comment]
Greyhole uses PHP's `mail()` function to send emails.
See [its documentation](http://php.net/manual/en/function.mail.php) for details.

I would guess it should always be able to send emails to local users.
Do you have `mailx` (or similar) installed? If so, simply executing `mail` as the user configured to receive the emails should so the emails this local account received.
I never had anything to do in order to be able to send emails to local users on all the Linux servers I worked on; not sure if Fedora 23 is somehow different.

**Comment by taa1** [comment]
Actually, installing and running mailx is what made me realize no MTA was installed -- it gave an error saying it couldn't find the sendmail binary so then I installed postfix, launched it, and suddenly mail to local users was working just fine. Thanks for the reply and info; I'll keep this in mind for the future.
