### ISSUE TITLE
Copies are not created when greyhole is paused, and the machine returns from a reboot

### ISSUE THREAD

**Issue by assafw** [gboudreau/Greyhole#224]
Hello,

An issue I noticed today:

Something I noticed today. Greyhole was paused (`greyhole --pause`).. I often do that when moving a bunch of large files to one of the shares and want the replication to happen once I'm done.

the daemon was left in a paused state, and then I rebooted the machine. When the machine was up again, and I started the service, it didn't pick up the tasks in the queue, it took a manual fsck on those shares (`greyhole --fsck -d /lz/<Share>`) to sort it out..

Cheers!

**Comment by gboudreau** [comment]
Indeed, when the daemon is not running (or paused), (some of) the spooled file operations are saved in a tmpfs (in RAM), because writing those to disk would be too slow. So a reboot would indeed wipe those.
Would need to think of a way to move those to disk automatically...

**Comment by assafw** [comment]
I was under the impression there is a task written immediately to the tasks table in mysql?

**Comment by gboudreau** [comment]
No; the Samba VFS module does the spooling of tasks, and to be as performant as possible, and the simplest possible, it just writes text files into the spool folder. The daemon reads those whenever it has nothing to do, and writes them in MySQL.  
For write operations in particular, the VFS module is getting called every time data is written to disk, which is VERY OFTEN, when writing large files, thus why it writes those in a folder that is a tmpfs. Writing those to a normal disk was slowing down Samba transfers, because Samba waits for the VFS modules before continuing to write.

I'll come up with something; probably try to move the spooled ops from disk/tmpfs to MySQL often, even when the daemon is not running, and doing so again when the init script is called to stop the service, during shutdown/reboot.

**Comment by gboudreau** [comment]
Version 0.12.3 includes a fix for this. It adds a crontab entry to run `greyhole --process-spool` every 5 seconds, and again when the service is stopped (by the init.d or equivalent script).
