### ISSUE TITLE
Trash Manager (WIP)

### ISSUE THREAD

**Issue by zefie** [gboudreau/Greyhole#245]
I had some old PHP code from the [pre-webui version of Greyhole](https://pastebin.com/BgAYQMaW) (note the timestamp on that pastebin) that I wrote to manage the trashes. I am working on bringing it into the Web-UI. So far just changed it to use the $stats var instead of read /etc/greyhole.conf and made it work with the web-ui to change pages. More work has to be done before I'm willing to submit any updated code, but wanted to see if you would be interested in the final product, or if you already had something else in the works.

![image](https://user-images.githubusercontent.com/612177/98483010-2f481000-21d3-11eb-8bf4-2502e7e85219.png)

**Comment by gboudreau** [comment]
No, I had nothing planned at the moment, regarding the trash.
Whenever you submit a PR, I'll review and merge.
Cheers.

**Comment by zefie** [comment]
I've managed to get it to work (tested on debian buster, greyhole 0.15.0, ext4).

There are some issues with the caching due to the ajax design. I am not sure if this was intentional when you wrote the web-ui, but some things don't update as one would expect.

For example, clicking "status" while on any page (including status) does not update the log, f5 or even ctrl-f5 is needed. Same with my newly injected trash manager. If I delete something, I have to refresh and not just click the tab for it to update.

**Comment by gboudreau** [comment]
Yeah, it is intentional. Data should be updated using AJAX calls. The logs in the Status tab is updated using a toggle "Follow (tail) status logs" (which will be enabled by default in the next version).
For your use-case, I would suggest creating a JSON version of the data to display (that contains both the list of files in the current dir, and the numbers below it), and use Javascript to load that using an AJAX GET request, then create the HTML needed (using jQuery). Call that when the user loads the screen, and after each operation, to display updated information.
I can help with all this, if you need. Should be pretty straightforward for me to convert a "regular" page created from PHP into what I describe above, so if you want me to help, send a PR which implements the rest, and I'll continue from there.

**Comment by zefie** [comment]
I submitted the current code I have via a [PR](https://github.com/gboudreau/Greyhole/pull/246).

**Comment by gboudreau** [comment]
Sorry, forgot about this for a while there.
Do you think this is stable enough now on your side for me to refactor things to using AJAX, and then merge?

**Comment by zefie** [comment]
It works well for my day-to-day use but I have not tested every Greyhole configuration possibility, nor am I willing to call it production ready (even if I am running in a private production env)

The main thing I don't know if it will work with "Move to trash old versions of modified files" option in Greyhole, as the code just looks for a copy of the file in .gh_trash and restores/deletes it if the user requests it. If the .gh_trash filename is changed (eg file-timestamp.ext) then the code may need some additional work to handle that.

That and the "copies" is incorrect for folders, as noted in the source code comments. This is mostly because I scrape the filesystem for the files and do not check any metadata in the database.

**Comment by gboudreau** [comment]
So I integrated this functionality in the existing UI, and used AJAX for everything (navigation, restore, delete forever).
Build 0.15.1 includes this.
Can you try it, see if maybe I missed something? I used quite a different technique to list files in the trash, and restore. Pretty much all the code change really!

**Comment by zefie** [comment]
Hmm, what is the safest way to upgrade from Debian distro/apt edition to development edition without breaking my setup?
If there is a way without damaging my existing pool, I can test this :)

Not surprised it needed a rewrite though, as the initial comments said it was basically hacked together in 2013 to do a thing I needed. I'm more surprised it worked as-is with the WebUI :)

**Comment by gboudreau** [comment]
If you are already using the apt version, just upgrade to 0.15.1; it contains this change.

**Comment by zefie** [comment]
Now it just doesn't work at all for me (the trash manager)
![CdzDKSq5a7](https://user-images.githubusercontent.com/612177/100649565-9d827d00-3310-11eb-8abf-a5f231ea8ee0.png)

**Comment by gboudreau** [comment]
So I fixed my Makefile to include `trash.php` (oops!)

As for displaying sizes in human-readable B/KiB/MiB/GiB, I chose to always display in bytes in the table (except for files), because it makes it much easier to see quickly what is big, vs what is small:
![image](https://user-images.githubusercontent.com/370329/100680655-059c8780-3340-11eb-9c0c-615363700b29.png)

vs a human-readable sizes version:
![image](https://user-images.githubusercontent.com/370329/100680714-311f7200-3340-11eb-8871-9801c7adb351.png)

Only the K, M or G characters in those can tell me what's big and what's small.

But with bytes, I don't even have to read the numbers; I can just know that the trash for the Videos share is taking a lot more space than the others, just by seeing the length of the size column.

In the modal prompt (to confirm delete and restore), I show the human-readable version, as at that point, you don't want to compare that value with others; you just (maybe) want to know the size.

And yes, the Datatable seems to have issues when the window gets resized. I read that it should adjust automatically, but it doesn't. I'll investigate, and might just hook the window.resize event manually to force a redraw.
